### ISSUE TITLE
update Readme

### ISSUE THREAD

**Issue by onemanstartup** [avit/schedule_attributes#5]
Please update current readme for current version.
I figure out to change schedule_yaml tp schedule, but don't know how to use formtastic helpers.

**Comment by avit** [comment]
Sorry 'bout that, I will update it. :-) It's substantially changed from previous forks.

**Comment by hallmatt** [comment]
Looks like a great tool. More examples using the form helpers would be great! Specifically, something like a repeating event on the 1st, 2nd, and 5th weeks on a Monday and Wednesday. 

@onemanstartup - You had to change the schedule_yaml column to schedule? I haven't tested much, because my implementation is in it's early stages, but it looked like it was saving a schedule in schedule_yaml, but I wasn't able to render it back out in an edit screen.

**Comment by avit** [comment]
The default column name is "schedule", which stores the serialized schedule. Reading the attribute through the model.schedule accessor returns the IceCube::Schedule object. You can change it with:

`has_schedule_attributes :column_name => "schedule_yaml"`

**Comment by avit** [comment]
@hallmatt In my application I haven't used the Nth week (`ordinal_week`) inputs since we neither need or want that level of complexity for our UI. I have a pending spec for it, if you want to open a separate issue for it so we can track that feature:

https://github.com/avit/schedule_attributes/blob/master/spec/schedule_attributes/rule_parser/month_spec.rb#L35

**Comment by avit** [comment]
Closing old tickets, pull requests welcome.
